### ISSUE TITLE
Issues with Formats with variable length

### ISSUE THREAD

**Issue by mowolf** [mowolf/ChatAnalyzer#8]
Most of the bugs come back to this...

**Comment by mowolf** [comment]
7/31/16, 1:11 PM - Yo: Ya viste esto? 7/31/16, 1:17 PM - Copy: Jaja no donde lo sacaste?

**Comment by Spinfuser** [comment]
[2/28/17, 3:54:36 PM] Name1: blabla
[2/28/17, 3:55:02 PM] Name2: blabla

"If you get this error even though this is no group chat search in your .txt file and replace this occurence:

ame2"

The file is quite big, over 5mb

**Comment by itsbayad** [comment]
I think I figured out the issue here. When you copy and paste a few messages from Whatsapp, it's the same format as the code analyzes, so if you send that as a message in a Whatsapp chat, the code will get lost because it'll see the date and contact name again after a date and contact name. Thus, it'll assume the " " in between them is the actual message, and that the new names of the pasted conversation are more people talking. That's why it reads like a group chat

**Comment by Spinfuser** [comment]
Seems like you fixed it sort of, but my chronological graph seems wrong, big gaps.

**Comment by mowolf** [comment]
@Spinfuser Yeah, there are still issues with some formats that have a variable length. Like 9:10 PM and 12:00 AM vs 09:10 PM and 12:00 AM.

**Comment by anujbiyani** [comment]
Using regex and libraries to parse dates+times would help a lot over the substring approach.

**Comment by mowolf** [comment]
All parsing is now done via regex. I still leave this open in case there are more issues.

**Comment by ryanb93** [comment]
These don't get removed:

`[21/04/2018, 10:50:45] ‎You added Firstname Lastname`

**Comment by mowolf** [comment]
@ryanb93 fixed. ;)
